### ISSUE TITLE
Factorization and Powerconverters

### ISSUE THREAD

**Issue by jznomoney** [zerotheliger/PowerConverters#15]
The newest Factorization release breaks powerconverters.  It crashes upon launch.

**Comment by zerotheliger** [comment]
do you have a crash report?

**Comment by jznomoney** [comment]
Line 38477: 2014-01-03 20:01:14 [SEVERE] java.lang.ClassNotFoundException: factorization.common.Core
Line 38483: 2014-01-03 20:01:14 [SEVERE]  at powercrystals.powerconverters.mods.Factorization.postInit(Factorization.java:45)
Line 38483: 2014-01-03 20:01:14 [SEVERE]  at powercrystals.powerconverters.mods.Factorization.postInit(Factorization.java:45)

**Comment by LemADEC** [comment]
Here's a more detailled log:

```
2014-02-02 13:32:03 [Le plus précis] [PowerConverters] Sending event FMLPostInitializationEvent to mod PowerConverters
2014-02-02 13:32:03 [Précis] [fml.ItemTracker] Adding item powercrystals.powerconverters.common.ItemBlockPowerConverterCommon(2850) owned by PowerConverters
2014-02-02 13:32:03 [Infos] [STDERR] java.lang.ClassNotFoundException: factorization.common.Core
2014-02-02 13:32:03 [Infos] [STDERR]    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
2014-02-02 13:32:03 [Infos] [STDERR]    at java.lang.ClassLoader.loadClass(Unknown Source)
2014-02-02 13:32:03 [Infos] [STDERR]    at java.lang.ClassLoader.loadClass(Unknown Source)
2014-02-02 13:32:03 [Infos] [STDERR]    at java.lang.Class.forName0(Native Method)
2014-02-02 13:32:03 [Infos] [STDERR]    at java.lang.Class.forName(Unknown Source)
2014-02-02 13:32:03 [Infos] [STDERR]    at powercrystals.powerconverters.mods.Factorization.postInit(Factorization.java:45)
2014-02-02 13:32:03 [Infos] [STDERR]    at powercrystals.powerconverters.mods.base.LoaderBase.load(LoaderBase.java:27)
2014-02-02 13:32:03 [Infos] [STDERR]    at powercrystals.powerconverters.PowerConverterCore.postInit(PowerConverterCore.java:98)
2014-02-02 13:32:03 [Infos] [STDERR]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-02-02 13:32:03 [Infos] [STDERR]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-02-02 13:32:03 [Infos] [STDERR]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-02-02 13:32:03 [Infos] [STDERR]    at java.lang.reflect.Method.invoke(Unknown Source)
2014-02-02 13:32:03 [Infos] [STDERR]    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
2014-02-02 13:32:03 [Infos] [STDERR]    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
2014-02-02 13:32:03 [Infos] [STDERR]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-02-02 13:32:03 [Infos] [STDERR]    at java.lang.reflect.Method.invoke(Unknown Source)
2014-02-02 13:32:03 [Infos] [STDERR]    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
2014-02-02 13:32:03 [Infos] [STDERR]    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2014-02-02 13:32:03 [Infos] [STDERR]    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
2014-02-02 13:32:03 [Infos] [STDERR]    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
2014-02-02 13:32:03 [Infos] [STDERR]    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
2014-02-02 13:32:03 [Infos] [STDERR]    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
2014-02-02 13:32:03 [Infos] [STDERR]    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
2014-02-02 13:32:03 [Infos] [STDERR]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-02-02 13:32:03 [Infos] [STDERR]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-02-02 13:32:03 [Infos] [STDERR]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-02-02 13:32:03 [Infos] [STDERR]    at java.lang.reflect.Method.invoke(Unknown Source)
2014-02-02 13:32:03 [Infos] [STDERR]    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
2014-02-02 13:32:03 [Infos] [STDERR]    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2014-02-02 13:32:03 [Infos] [STDERR]    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
2014-02-02 13:32:03 [Infos] [STDERR]    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
2014-02-02 13:32:03 [Infos] [STDERR]    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
2014-02-02 13:32:03 [Infos] [STDERR]    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
2014-02-02 13:32:03 [Infos] [STDERR]    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:704)
2014-02-02 13:32:03 [Infos] [STDERR]    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:249)
2014-02-02 13:32:03 [Infos] [STDERR]    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:509)
2014-02-02 13:32:03 [Infos] [STDERR]    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
2014-02-02 13:32:03 [Infos] [STDERR]    at net.minecraft.client.main.Main.main(SourceFile:101)
2014-02-02 13:32:03 [Infos] [STDERR]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-02-02 13:32:03 [Infos] [STDERR]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-02-02 13:32:03 [Infos] [STDERR]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-02-02 13:32:03 [Infos] [STDERR]    at java.lang.reflect.Method.invoke(Unknown Source)
2014-02-02 13:32:03 [Infos] [STDERR]    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
2014-02-02 13:32:03 [Infos] [STDERR]    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
2014-02-02 13:32:03 [Infos] [STDERR] Caused by: java.lang.NullPointerException
2014-02-02 13:32:03 [Le plus précis] [PowerConverters] Sent event FMLPostInitializationEvent to mod PowerConverters
```

Using Factorization-0.8.29.jar & PowerConverters-1.6.4-39.zip
